name: Xcodebuild

on: push
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: pod install
    - name: Build and test
      run: xcodebuild test -workspace 'ios-actions-demo.xcworkspace' -scheme 'ios-actions-demo' -destination 'platform=iOS Simulator,name=iPhone 11'